/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Mnojestvo;

import java.util.HashSet;

public class MySet {
    private HashSet<Object> set;

    public MySet() {
        set = new HashSet<>();
    }

    public boolean add(Object element) {
        return set.add(element);
    }

    public boolean contains(Object element) {
        return set.contains(element);
    }

    public void remove(Object element) {
        set.remove(element);
    }

    public int size() {
        return set.size();
    }
}